# Generated by Django 6.0 on 2026-02-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_servicecategory_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Hairdresser, Makeup Artist', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('working_days', models.CharField(help_text='Comma-separated days, e.g. Mon,Tue,Wed', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='salon.salon')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
